version: '3'
services:
    web-application:
        build:
            context: 'web-application/'
            dockerfile: './src/presentation-layer/Dockerfile'
        ports:
            - '8080:8080'
            - '9229:9229'
        volumes:
            - './web-application/src:/web-application/src'
        depends_on:
            - database

    rest-api:
        build:
            context: 'web-application/'
            dockerfile: './src/presentation-layer-api/Dockerfile'
        ports:
            - '3000:3000'
        volumes:
            - './web-application/src:/web-application/src'
        depends_on:
            - database

    database:
        build: ./db
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=elpassword123
            - MYSQL_DATABASE=webAppDatabase

    redis:
        build: ./redis-db
        command: redis-server --requirepass elpassword123
        ports:
            - '6379:6379'
