version: '3'
networks:
    app-tier:
        driver: bridge
services:
    'web-application':
        build: './web-application'
        ports:
            - '8080:8080'
            - '9229:9229'
        volumes:
            - './web-application/src:/web-application/src'
        depends_on:
            - database
    database:
        build: ./db
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=elpassword123
            - MYSQL_DATABASE=webAppDatabase
    redis:
        build: ./redis-db
        command: redis-server --requirepass elpassword123
        ports:
            - '6379:6379'
